# ~/.config/starship.toml
# Starship prompt configuration

format = """
$os$username$hostname$directory$git_branch$git_status$python$nodejs$rust$golang$package$memory_usage$cmd_duration
$character"""

# Allow a bit more time for slower commands (git status, node)
command_timeout = 2000

# Disable the blank line at the start of the prompt
add_newline = false

# OS module
[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Alpaquita = "ğŸ””"
Alpine = "ğŸ”ï¸"
Amazon = "ğŸ™‚"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
Artix = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
DragonFly = "ğŸ‰"
Emscripten = "ğŸ”—"
EndeavourOS = "ğŸš€"
Fedora = "ğŸ©"
FreeBSD = "ğŸ˜ˆ"
Garuda = "ğŸ¦…"
Gentoo = "ğŸ—œï¸"
HardenedBSD = "ğŸ›¡ï¸"
Illumos = "ğŸ¦"
Linux = "ğŸ§"
Mabox = "ğŸ“¦"
Macos = "ğŸ"
Manjaro = "ğŸ¥­"
Mariner = "ğŸŒŠ"
MidnightBSD = "ğŸŒ˜"
Mint = "ğŸŒ¿"
NetBSD = "ğŸš©"
NixOS = "â„ï¸"
OpenBSD = "ğŸ¡"
OpenCloudOS = "â˜ï¸"
openEuler = "ğŸ¦Œ"
openSUSE = "ğŸ¦"
OracleLinux = "ğŸ¦´"
Pop = "ğŸ­"
Raspbian = "ğŸ“"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"
Redox = "ğŸ§ª"
Solus = "â›µ"
SUSE = "ğŸ¦"
Ubuntu = "ğŸ¯"
Unknown = "â“"
Windows = "ğŸªŸ"

# Username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Directory
[directory]
truncation_length = 3
truncation_symbol = 'â€¦/'
home_symbol = 'ó°‹œ ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Git
[git_branch]
symbol = ' '
format = 'on [$symbol$branch]($style)'
truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'green'

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = 'green'
conflicted = 'ğŸ³'
up_to_date = ' '
untracked = ' '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = 'è¥ '
deleted = ' '

# Languages
[python]
symbol = ' '
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'yellow'

[nodejs]
format = 'via [ $version](green) '
disabled = false

[rust]
format = 'via [ $version](red) '

[golang]
format = 'via [ $version](cyan) '

# Package version
[package]
format = 'is [ $version](208 bold) '

# Memory usage
[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'cyan'
format = 'via $symbol[$ram( | $swap)]($style) '

# Command duration
[cmd_duration]
format = 'took [$duration](yellow) '
min_time = 2_000

# Character
[character]
success_symbol = '[â¯](purple)'
error_symbol = '[â¯](red)'
vimcmd_symbol = '[â®](green)'
